kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: system-msg
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30104
  type: NodePort
