apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka1
  namespace: system-msg
spec:
  replicas: 1
  selector:
    app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: docker.registry.local:5000/kafka-addon:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "30101"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.0.15.101
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka2
  namespace: system-msg
spec:
  replicas: 1
  selector:
    app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: docker.registry.local:5000/kafka-addon:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "30102"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.0.15.102
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka3
  namespace: system-msg
spec:
  replicas: 1
  selector:
    app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: docker.registry.local:5000/kafka-addon:v1.${BUILD_NUMBER}
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_PORT
          value: "30103"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.0.15.103
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
