apiVersion: v1
kind: Service
metadata:
  name: kaf1
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.101
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30101
      protocol: TCP
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.102
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30102
      protocol: TCP
  selector:
    app: kafka2
---
apiVersion: v1
kind: Service
metadata:
  name: kaf3
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.103
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30103
      protocol: TCP
  selector:
    app: kafka3
