kind: Service
apiVersion: v1
metadata:
  name: kaf1-exporter
  namespace: system-msg
spec:
  ports:
  - name: port-7071
    port: 7071
    protocol: TCP 
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf1
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.101
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30101
      protocol: TCP
  selector:
    app: kafka1
---
kind: Service
apiVersion: v1
metadata:
  name: kaf2-exporter
  namespace: system-msg
spec:
  ports:
  - name: port-7071
    port: 7071
    protocol: TCP 
  selector:
    app: kafka2
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.102
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30102
      protocol: TCP
  selector:
    app: kafka2
---
kind: Service
apiVersion: v1
metadata:
  name: kaf3-exporter
  namespace: system-msg
spec:
  ports:
  - name: port-7071
    port: 7071
    protocol: TCP 
  selector:
    app: kafka3
---
apiVersion: v1
kind: Service
metadata:
  name: kaf3
  namespace: system-msg
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.15.103
  ports:
    - name: port-9092
      port: 9092
      nodePort: 30103
      protocol: TCP
  selector:
    app: kafka3
